### ISSUE TITLE
Theme tweaks based on feedback

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/ol-keycloak#45]
### Acceptance Criteria
- [x] The account page isn't styled (user ends up here if they have missing profile information and "login" via a password reset)
- [x] The login page where a user enters missing user/profile information hasn't been styled (different than the account page)
- [x] Use "Log in" and "Sign up" wording in all places
- [x] Rename usages like "Forgot Password" to "Reset Password"

**Comment by pdpinch** [comment]
@rhysyngsun you checked this box, but I don't think it's working. 

> The page where a user enters missing user/profile information hasn't been styled.

I tried to log in via discussions-rc.odl.mit.edu using an existing account. Because these accounts don't share first name and last name, I was forced into the [Personal Info page on keycloak](https://sso-qa.ol.mit.edu/realms/olapps/account/) which has the default Keycloak styling:

<img width="1512" alt="image" src="https://github.com/mitodl/ol-keycloak/assets/430126/375361ab-f267-4b46-a13e-bd3e95af2a8a">

**Comment by pdpinch** [comment]
My [comment](https://github.com/mitodl/ol-keycloak/issues/45#issuecomment-2032777228) is out of scope for this issue. We'll open another issue to address it.
